require('options/treesitter')
require('options/telescope')
require('options/lsp')
require('options/cmp')
require('options/colorizer')
require('options/ale')
require('options/fzf')
require('options/golang')
require('options/lualine')

require('gitsigns').setup()
require("bufferline").setup({})
require('trouble').setup({})
