#!/usr/bin/env bash

TEMP_DIR="/tmp/${USER}-temp"

if [ ! -d "${TEMP_DIR}" ]; then
  mkdir "${TEMP_DIR}" && chown 700 "${TEMP_DIR}"
fi
if [ ! -L "$HOME/temp" ]; then
  ln -s "${TEMP_DIR}" "$HOME/temp"
fi
