#!/usr/bin/env bash

function aws-to-env {
  # Gather AWS credentials if not set in the environment
  # This will grab the _first_ set of credentials it finds in ~/.aws/credentials
  if [ -e ~/.aws/credentials ]; then
    if [ -z ${AWS_ACCESS_KEY_ID+x} ]; then
      AWS_ACCESS_KEY_ID=$(awk '/aws_access_key_id/ {print $3; exit}' ~/.aws/credentials)
    fi

    if [ -z ${AWS_SECRET_ACCESS_KEY+x} ]; then
      AWS_SECRET_ACCESS_KEY=$(awk '/aws_secret_access_key/ {print $3; exit}' ~/.aws/credentials)
    fi
  fi

  # Set the default region
  if [ -e ~/.aws/config ]; then
    if [ -z ${AWS_DEFAULT_REGION+x} ]; then
      AWS_DEFAULT_REGION=$(awk '/region/ {print $3; exit}' ~/.aws/config)
    fi
  fi

  export AWS_ACCESS_KEY_ID
  export AWS_SECRET_ACCESS_KEY
  export AWS_DEFAULT_REGION
}
